version: "2"

services:
  node:
    build: .
    ports:
      - 3000:3000
    links:
      - mongo
  
  mongo:
    image: mongo
    volumes:
      - ~/Code/data/db:/data/db
    ports:
      - 27017:27017